name: Lint

# We ignore the dangerous-triggers warning because forked PRs
# require repo secrets to run some of the defined checks,
# and we protect against malicious actors by requiring approval
# for all external contributors before workflows will run.
on: pull_request_target # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: masterpointio/.github/.github/workflows/lint.yaml@6f1be5090fc5c310fc293d5abd3a5ce67d4be1c5
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
