name: Lint

# We ignore the dangerous-triggers warning because forked PRs
# require repo secrets to run some of the defined checks,
# and we protect against malicious actors by requiring approval
# for all external contributors before workflows will run.
on: pull_request_target # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: masterpointio/actions/.github/workflows/lint.yaml@06de5f4f74e246a9039b4f58baca9c79c3c1fd05
    with:
      head-ref: ${{ (github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number)) || github.event.pull_request.head.sha || github.sha }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
