name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-please:
    uses: glaracuente/gerry-actions/.github/workflows/release-please.yaml@65176ec77889b6628371c3db3dc6b279a9788176
    with:
      release-type: terraform-module
    secrets:
      MP_BOT_APP_ID: ${{ secrets.MP_BOT_APP_ID }}
      MP_BOT_APP_PRIVATE_KEY: ${{ secrets.MP_BOT_APP_PRIVATE_KEY }}
    permissions:
      contents: write # needed by release-please-action
      pull-requests: write # needed by release-please-action
      issues: write # needed by release-please-action
