name: TF Test

on:
  push:
    branches:
      - main
  pull_request_target:

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pull-requests: read

jobs:
  tf-test:
    name: 🧪 ${{ matrix.tf }} test
    runs-on: ubuntu-latest
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
    strategy:
      matrix:
        tf: [tofu, terraform]
    steps:
      - uses: masterpointio/github-action-tf-test@v1.0.1
        with:
          tf_type: ${{ matrix.tf }}
          aws_role_arn: ${{ vars.TF_TEST_AWS_ROLE_ARN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
