name: Zizmor

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    uses: masterpointio/.github/.github/workflows/zizmor.yaml@8faad24219c6897ee567cdc4b1af8d62a891398b
