name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    uses: masterpointio/.github/.github/workflows/zizmor.yml@5b6a1958f98df1c9bbe63b7920f6f7bb9bd68f87
    secrets: inherit
