name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    uses: masterpointio/.github/.github/workflows/zizmor.yml@chore/INT-1582/add_mp_workflows
    secrets: inherit
