name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    uses: masterpointio/.github/.github/workflows/zizmor.yml@6f1be5090fc5c310fc293d5abd3a5ce67d4be1c5
    secrets: inherit
